/**
 * Copyright (c) UIB GmbH <info@uib.de>
 * License: AGPL-3.0
 * This file is part of opsi - https://www.opsi.org
 */

package de.uib.configed.gui.share.table.gui;

/**
 * Enum for identifying filter state keys in FilterStateManager.
 */
public enum FilterKey {
	DEPOT_PRODUCT_PROPERTIES_TABLE, CLIENT_TABLE, LOCALBOOT_PRODUCTS_TABLE, NETBOOT_PRODUCTS_TABLE,
	LICENSE_POOL_ENTER_TABLE, LICENSE_POOL_USAGE_TABLE, LICENSE_POOL_POOLS_TABLE, LICENSE_KEYS_EDIT_TABLE,
	LICENSE_KEYS_ENTER_TABLE, LICENSE_SOFTWARE_TABLE, LICENSE_CONTRACTS_EDIT_TABLE, LICENSE_CONTRACTS_ENTER_TABLE,
	LICENSE_USAGE_TABLE, LICENSE_RECONCILIATION_TABLE, LICENSES_STATISTICS_TABLE,
	LICENSE_PRODUCT_ID_TO_LICENSE_POOL_TABLE, LICENSE_REGISTERED_SOFTWARE_TABLE
}
