run_tests:
    image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default
    
    artifacts:
        name: 'configed-build'
        paths:
         - configed.jar

        expire_in: 2 day


    before_script:
        - apt-get update
        - apt-get --assume-yes install maven openjdk-8-jdk

    script:
        - mvn package -Dmaven.test.skip
