image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build
  - analize
  - sign

compile_and_package:
  image: maven:3.6.3-jdk-11
  stage: build
  script:
    - mvn package -Dmaven.test.skip

  artifacts:
    name: 'configed-build'
    paths:
      - target/configed-4.2.15.1.1-SNAPSHOT-jar-with-dependencies.jar
    expire_in: 2 day


sonarqube-check:
  stage: analize
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn verify sonar:sonar -Dsonar.projectKey=configed:configed || true
  allow_failure: true
  only:
    - main # or the name of your main branch


signandupload:
  stage: sign
  script:
    - opsi-dev-tool -l info --signserver-sign target/configed-4.2.15.1.1-SNAPSHOT-jar-with-dependencies.jar || true
#    - version=$(cat configed.version)
#    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push configed.jar configed all all $version "$CI_JOB_ID"'
#    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push configed.jar configed all all $version'

