image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default


stages:          # List of stages for jobs, and their order of execution
  - build


compile_and_package:
  image: openjdk:8
  stage: build
  before_script:
    - apt-get --assume-yes install maven openjdk-8-jdk
  script:
    - mvn package -Dmaven.test.skip

  artifacts:
    name: 'configed-build'
    paths:
      - configed.jar
      - configed.version
    expire_in: 2 day
