image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build
  - sign

compile_and_package:
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes install maven openjdk-8-jdk
  script:
    - mvn package -Dmaven.test.skip

  artifacts:
    name: 'configed-build'
    paths:
      - target/configed-4.2.15.1.1-SNAPSHOT-jar-with-dependencies.jar
    expire_in: 2 day


signandupload:
  stage: sign
  script:
    - opsi-dev-tool -l info --signserver-sign target/configed-4.2.15.1.1-SNAPSHOT-jar-with-dependencies.jar
#    - version=$(cat configed.version)
#    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push configed.jar configed all all $version "$CI_JOB_ID"'
#    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push configed.jar configed all all $version'

