image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - set_variables
  - build_and_analyze
  - sign
  - make_opsiproduct

set_variables:
  stage: set_variables
  script:
    - CONFIGED_VERSION=$(sed -n 's,.*<version>\(.*\)</version>.*,\1,p' pom.xml | head -1)
    - CONFIGED_JAR_NAME="configed-${CONFIGED_VERSION}.jar"
    - CONFIGED_JAR_NAME_WITH_DEPS="configed-${CONFIGED_VERSION}-jar-with-dependencies.jar"
    - echo "CONFIGED_VERSION=$CONFIGED_VERSION" > version-and-jar.env
    - echo "CONFIGED_JAR_NAME=$CONFIGED_JAR_NAME" >> version-and-jar.env
    - echo "CONFIGED_JAR_NAME_WITH_DEPS=$CONFIGED_JAR_NAME_WITH_DEPS" >> version-and-jar.env
  artifacts:
    reports:
      dotenv:
        - version-and-jar.env
    expire_in: 2 day

compile_and_package:
  image: maven:3.8.6-openjdk-18
  stage: build_and_analyze
  script:
    - mvn package
    - jdeps --class-path target/$CONFIGED_JAR_NAME_WITH_DEPS --recursive --ignore-missing-deps --list-deps target/$CONFIGED_JAR_NAME | grep -v "java.base/sun.nio.ch" > target/module.deps
    # jdk.crypto.ec is needed for TLS (HTTPS)
    - echo "   jdk.crypto.ec" >> target/module.deps
    - cat target/module.deps
  artifacts:
    name: "configed-build"
    paths:
      - target/$CONFIGED_JAR_NAME_WITH_DEPS
      - target/module.deps
    expire_in: 2 day
  needs:
    - set_variables

sonarqube-check:
  stage: build_and_analyze
  image: maven:3.8.6-openjdk-18
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn sonar:sonar -Dsonar.projectKey=configed
  only:
    - main # or the name of your main branch

signandupload:
  stage: sign
  script:
    - echo "CI_JOB_ID_CONFIGED=$CI_JOB_ID" > ci_job_id.env
    - opsi-dev-tool -l info --signserver-sign target/$CONFIGED_JAR_NAME_WITH_DEPS
    - mkdir opsi-configed
    - mv target/$CONFIGED_JAR_NAME_WITH_DEPS target/module.deps opsi-configed/
    - cp CHANGELOG.md opsi-configed/
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push opsi-configed configed all all $CONFIGED_VERSION "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push opsi-configed configed all all $CONFIGED_VERSION'
  needs:
    - set_variables
    - compile_and_package
  artifacts:
    reports:
      dotenv:
        - ci_job_id.env
    expire_in: 2 day

trigger_opsiproduct_pipeline:
  stage: make_opsiproduct
  script:
    - '[ "$CI_COMMIT_TAG" = "" ] || CONFIGED_PRERELEASE_VERSION=""'
    - '[ "$CI_COMMIT_TAG" = "" ] && CONFIGED_PRERELEASE_VERSION="$CI_JOB_ID_CONFIGED"'
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master --form "variables[CONFIGED_PRERELEASE_VERSION]=$CONFIGED_PRERELEASE_VERSION" --form "variables[CONFIGED_VERSION]=$CONFIGED_VERSION" --form "variables[CONFIGED_JAR_NAME_WITH_DEPS]=$CONFIGED_JAR_NAME_WITH_DEPS" --form "variables[PIPELINE_COMMIT_TAG]=$CI_COMMIT_TAG"   "https://gitlab.uib.gmbh/api/v4/projects/427/trigger/pipeline"
  needs:
    - set_variables
    - compile_and_package
    - signandupload
