image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build

compile_and_package:
  image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes install maven openjdk-8-jdk
  script:
    - MVN_VERSION=$(mvn -q -Dexec.executable=echo Dexec.args='${project.version}' --non-recursive exec:exec)
    - mvn package -Dmaven.test.skip

  artifacts:
    name: 'configed-build'
    paths:
      - target/configed-${MVN_VERSION}-jar-with-dependencies.jar
    expire_in: 2 day
